### ISSUE TITLE
removing "looking for a maintainer"

### ISSUE THREAD

**Issue by vindarel** [myfreeweb/django-mode#23]
Hi, I've seen reactions of some people that read the big "need a maintainer" statement: they didn't even try the mode and re-implemented some of its features :( Would you mind writing something else, maybe somewhere else ? Like just "looking for a new maintainer" after the package description, or "slow maintainance" ('cause we are a few people watching (and using) this mode).
Thanks.

**Comment by myfreeweb** [comment]
okay.

> re-implemented some of its features

hmm where??

Actually maybe you could take over the project? :)

**Comment by vindarel** [comment]
At least here on Elpy: https://github.com/jorgenschaefer/elpy/pull/1042 I left a comment, questionning the approach and speaking about django-mode.

> Actually maybe you could take over the project? :)

Today I feel like it. I remember you proposed quite some time ago and I rejected, later I suggested that again and you didn't pay attention. So now, let's go ?! :) 

I'd like to bring hydras and integration with elpy's test runner feature. Actually I have the required changes in place but the elpy integration is more difficult (last time I and elpy's maintainer had a difficult conversation, we didn't quite understand each other :/ )

ps: and for someone reading, and for my curriculum :p I also have packages here: https://gitlab.com/emacs-stuff/

**Comment by myfreeweb** [comment]
Okay, invited you to the collaborator access thing.

**Comment by vindarel** [comment]
done, thanks.
